### ISSUE TITLE
AttributeError: 'SessionRenegotiationScanResult' object has no attribute 'accepts_client_renegotiation'

### ISSUE THREAD

**Issue by drboone** [F5-Labs/cryptonice#29] opened 2021-05-28 19:21 UTC
Python 3.9.2
Cryptonice 1.3.4 installed from pip
```
# cryptonice networks.h-net.org --tls all
Pre-scan checks
-------------------------------------
Scanning networks.h-net.org on port 443...
Analyzing DNS data for networks.h-net.org
Fetching additional records for networks.h-net.org
networks.h-net.org resolves to 35.9.18.76
35.9.18.76:443: OPEN
TLS is available: True
Connecting to port 443 using HTTPS
Reading HTTP headers for networks.h-net.org
Queueing TLS scans (this might take a little while...)
Traceback (most recent call last):
  File "/usr/local/bin/cryptonice", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/cryptonice/__main__.py", line 104, in main
    output_data, hostname = scanner_driver(input_data)
  File "/usr/local/lib/python3.9/dist-packages/cryptonice/scanner.py", line 437, in scanner_driver
    tls_data = tls_scan(ip_address, str_host, commands_to_run, port)
  File "/usr/local/lib/python3.9/dist-packages/cryptonice/gettls.py", line 551, in tls_scan
    {'accepts_client_renegotiation': renegotiation_results.accepts_client_renegotiation})
AttributeError: 'SessionRenegotiationScanResult' object has no attribute 'accepts_client_renegotiation'
```

**Comment by warburtr0n** [comment] 2021-06-29 15:50
Sorry for the delay in looking at this @drboone 

Can you try version 1.3.6.4 (uploaded today) and let me know how you get on? I have previously removed some code related to old versions of SSLyze and I was unable to reproduce the error with this version of Cryptonice.

I'll close this issue for now but feel free to re-open if you believe it's still a problem.

**Comment by drboone** [comment] 2021-06-29 16:11
I'll try it.  Thanks!

**Comment by warburtr0n** [comment] 2021-06-29 16:12
Re-opened, this is an issue caused by a change in the SSLyze API. Version 1.3.7.0 (just uploaded) should resolve this, but please do test and let me know. Thanks!

**Closed as completed** 2021-06-29 16:26 UTC
Labels: bug

**Comment by drboone** [comment] 2021-06-29 17:09
1.3.7.0 successfully completed the command which failed in the initial report.  Thanks for the fix!
